language: python
python:
  - '3.8'
branches:
  only:
    - main
before_install:
  - openssl aes-256-cbc -K $encrypted_8e8be7063581_key -iv $encrypted_8e8be7063581_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 400 ~/.ssh/id_rsa
install:
  - pip install ansible
jobs:
  include:
  - stage: deploy-staging
    script: ansible-playbook -i ansible/inventory.yml ansible/playbook.yml --user $ANSIBLE_USER --private-key ~/.ssh/id_rsa
