# remember path base playbook yml

- name: run in local
  hosts: localhost
  tasks:
      - name: remove existing app bundle
        command: rm -rf ../build.tgz
      - name: create application bundle
        command: tar -zcvf build.tgz ../.

- name: run in remote server
  hosts: all
  tasks:
      - name: clear previous app directory
        ansible.builtin.file:
            path: "{{ ansible_facts['env']['HOME'] }}/app"
            state: absent
      - name: create new app directory
        ansible.builtin.file:
            path: "{{ ansible_facts['env']['HOME'] }}/app"
            state: directory
      - name: copy builded project to app directory server
        ansible.builtin.copy:
            src: build.tgz
            dest: "{{ ansible_facts['env']['HOME'] }}/app/build.tgz"
      - name: extract app bundle
        command: >
            tar -xvzf build.tgz
        args:
            chdir: app/